fix the bug for transient errors
SeanFeldman/ServiceBus.AttachmentPlugin pull request #277
Opened 2022-08-04 21:11 UTC by rmt-2021

### Fix #258 
### Bug description
We found that transient network errors (server busy) in [this line](https://github.com/SeanFeldman/ServiceBus.AttachmentPlugin/blob/a3739a16ceb0a4a10a23b7f82c3ff868a0ee019d/src/ServiceBus.AttachmentPlugin/AzureStorageAttachment.cs#L49), and the output error message is `Microsoft.Azure.Storage.StorageException : The specified container does not exist`.
More precisely, if the `container.ExistsAsync()` fails due to transient error(like service unavailable), the exception will be swallowed by the `catch` block without being checked. Therefore, the following [line of code](https://github.com/SeanFeldman/ServiceBus.AttachmentPlugin/blob/a3739a16ceb0a4a10a23b7f82c3ff868a0ee019d/src/ServiceBus.AttachmentPlugin/AzureStorageAttachment.cs#L66) will fail due to container not found exception.
```
try
{
    // Will only work for Shared Key or Account SAS. For Container SAS will throw an exception.
    if (! await container.ExistsAsync().ConfigureAwait(false))
    {
        await container.CreateIfNotExistsAsync().ConfigureAwait(false);
    }
}
catch (StorageException)
{
    // swallow in case a container SAS is used
}
...
await blob.UploadFromByteArrayAsync(message.Body, 0, message.Body.Length).ConfigureAwait(false);
```
### How to reproduce
Transient errors like 503 service unavailable are likely to happen when creating container, consequently the method `container.ExistsAsync()` will fail. Hence, [this line](https://github.com/SeanFeldman/ServiceBus.AttachmentPlugin/blob/a3739a16ceb0a4a10a23b7f82c3ff868a0ee019d/src/ServiceBus.AttachmentPlugin/AzureStorageAttachment.cs#L66) will fail due to container not found exception.
### Expected behaviour
The exception should be checked in the catch block to decide whether to swallow/retry/rethrow depending on the exception type. For example, if it is caused by some transient error, it can either retry or just rethrow the exception. (copied from #258)
### **Additional context**
This bug is similar to the #258 we found. We are willing to send a PR to help on this issue, if retry/rethrow the transient error exception is considered as a better practice than swallow.

2022-08-04 21:14 UTC, SeanFeldman commented
:white_check_mark: [Build ServiceBus.AttachmentPlugin 0.0.1039-preview completed](https://ci.appveyor.com/project/seanfeldman/servicebus-attachmentplugin/builds/44378629) (commit https://github.com/SeanFeldman/ServiceBus.AttachmentPlugin/commit/a380c9d580 by @rmt-2021)

2022-08-05 04:11 UTC, SeanFeldman requested changes

2022-08-05 04:11 UTC, SeanFeldman commented on src/ServiceBus.AttachmentPlugin/AzureStorageAttachment.cs
> +                    throw exception;
@rmt-2021, if I understand the change correctly, the caught exception should be rethrown here, but it should be rethrown, not throw a new exception by re-using the captured exception object. If I got it right, I suggest changing the rethrow code to follow the .NET standard exception rethrowing practice.

```suggestion
                if (exception.RequestInformation.HttpStatusCode != (int)System.Net.HttpStatusCode.Forbidden)
                {
                    throw;
                }
```

2022-08-05 04:11 UTC, SeanFeldman commented on src/ServiceBus.AttachmentPlugin/AzureStorageAttachment.cs
> +                    throw exception;
If you agree, you can `Commit suggestion,` and I'll merge the PR.

2022-08-06 22:37 UTC, rmt-2021 commented
Thanks for your suggestion! I have made the`Commit suggestion`.

2022-08-06 22:38 UTC, SeanFeldman commented
:white_check_mark: [Build ServiceBus.AttachmentPlugin 0.0.1040-preview completed](https://ci.appveyor.com/project/seanfeldman/servicebus-attachmentplugin/builds/44394507) (commit https://github.com/SeanFeldman/ServiceBus.AttachmentPlugin/commit/195d850d5b by @rmt-2021)

2022-08-06 23:44 UTC, SeanFeldman approved these changes

2022-08-06 23:49 UTC, merged

2022-08-06 23:51 UTC, SeanFeldman commented
@rmt-2021 Thank you for raising this PR.

Please note that the plugin is deprecated as the Service Bus it was developed for is also deprecated. I'm keeping the repo around for legacy projects but no longer publishing to NuGet.